### ISSUE TITLE
被ban了

### ISSUE THREAD

**Issue by lxyddice** [chenmy1903/LunarClient-CN#2]
没有任何开纪
理由是客户端有问题吗？
![uTools_1667980784532](https://user-images.githubusercontent.com/95132858/200775132-a5593a2d-a058-4619-9df1-f928fa856594.png)
![uTools_1667980867442](https://user-images.githubusercontent.com/95132858/200775138-5f5b7c3b-1ec4-4066-a945-8d81b3ba3649.png)

**Comment by chenmy1903** [comment]
LunarClient-CN没对游戏进行修改啊:|
是不是把hitdealyfix放进去了

**Comment by chenmy1903** [comment]
应该是zqat反作弊，之前误ban过我两次:|
